<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Ernaehrungsplan" nsURI="http://www.example.org/Ernaehrungsplan"
    nsPrefix="Ernaehrungsplan">
  <eClassifiers xsi:type="ecore:EClass" name="Ernaehrungsplan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="enthaelt" lowerBound="1"
        upperBound="-1" eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bestehtAus" upperBound="-1"
        eType="#//Gericht" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kcal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gericht">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kommentar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hauptbestandteil" eSuperTypes="#//Zutat"/>
  <eClassifiers xsi:type="ecore:EClass" name="Beilage" eSuperTypes="#//Zutat"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sosse" eSuperTypes="#//Zutat"/>
  <eClassifiers xsi:type="ecore:EClass" name="Salat" eSuperTypes="#//Zutat"/>
  <eClassifiers xsi:type="ecore:EClass" name="Zutat">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bestehtAus" lowerBound="1"
        upperBound="-1" eType="#//Gericht" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kcal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
